from nqrduck_spectrometer.base_spectrometer import BaseSpectrometer
from nqrduck_spectrometer_limenqr.model import LimeNQRModel
from nqrduck_spectrometer_limenqr.view import LimeNQRView
from nqrduck_spectrometer_limenqr.controller import LimeNQRController

LimeNQR = BaseSpectrometer(LimeNQRModel, LimeNQRView, LimeNQRController)